### PR TITLE
F/75mm avionics bay

### PR DESCRIPTION
**Pull request by kimanimichael**
Ready for launch

### CODE REVIEW

**Comment by ianmuchyri** [comment]
The battery holder length is an issue. From inspecting the measurement is around 8mm. The battery holder length should be around 14mm to account form the 10mm of the battery and some space for the XT60 and switch from the battery

**Comment by SammyOina** [comment]
add groves to top and bottom for insertion of mid part and send them off to be printed asp

**Comment by SammyOina** [comment]
> The battery holder length is an issue. From inspecting the measurement is around 8mm. The battery holder length should be around 14mm to account form the 10mm of the battery and some space for the XT60 and switch from the battery

I think it doesn't have to be that tall because it is much wider, so there's more volume for the battery

**Comment by kimanimichael** [comment]
> The battery holder length is an issue. From inspecting the measurement is around 8mm. The battery holder length should be around 14mm to account form the 10mm of the battery and some space for the XT60 and switch from the battery

I think you meant to use cm since the battery holder is 80mm long as of now.

**Comment by kimanimichael** [comment]
> add groves to top and bottom for insertion of mid part and send them off to be printed asp

Done

**Comment by ianmuchyri** [comment]
> > The battery holder length is an issue. From inspecting the measurement is around 8mm. The battery holder length should be around 14mm to account form the 10mm of the battery and some space for the XT60 and switch from the battery
> 
> I think you meant to use cm since the battery holder is 80mm long as of now.

yes. sorry

**Review by ianmuchyri — APPROVED** [review]

**Pull request merged**
